##############################
#### INTERFACE PARAMETERS ####
##############################
interface:
  theme: theme-dark
  transition:
    page: 200
  languages:
    available:
      - fr
      - en
    current: en
#########################
#### GAME PARAMETERS ####
#########################
game:
  score:
    increments:
      default: 1
      movement: 1
    intervals:
      default: 100
      movement: 20
    modifiers:
      pitfalls: 500
      bonus: -250
  tolerance:
    flag: 500
    target: 200
    pitfalls: 500
    bonus: 200
  visibility:
    bonus: 1500
  speed: 5000
  routing: 13.5
###########################
#### FORM DEFINITION ######
###########################
form:
  - question: 'Gender (select all relevant answers):'
    mandatory: false
    multiple: true
    answers:
      - text: Woman
        unique: false
      - text: Man
        unique: false
      - text: Transgender
        unique: false
      - text: Prefer not to answer
        unique: true
  - question: 'Select your age category:'
    mandatory: false
    multiple: false
    answers:
      - text: 18-24
        unique: true
      - text: 25-34
        unique: true
      - text: 35-44
        unique: true
      - text: 45-59
        unique: true
      - text: 60 and above
        unique: true
      - text: Prefer not to answer
        unique: true
  - question: 'You use interactive maps:'
    mandatory: false
    multiple: false
    answers:
      - text: Every day
        unique: true
      - text: A few times a week
        unique: true
      - text: A few times a month
        unique: true
      - text: Almost never
        unique: true
      - text: Prefer not to answer
        unique: true

#############################
#### TUTORIAL DEFINITION ####
#############################
tutorial:
  start:
    zoom: 5
    center: [ 270845.15,5904541.30 ]
  player: [ 396377.1,5701254.9 ]
  target: [ 416553.587,5708562.378 ]
  hints:
    0: You are in the west of the city of Lyon
    6: You are between St-Étienne and Clermont-Ferrand
    8: You are south-west of Ambert
    10: You are between St-Amant-Roche-Savine and St-Germain-l'Herm
    11: You are south-west of Fournols
    13: You are in La Colombière, double-tap on your position
  pitfalls:
    - [ 399537.1,5699198.9 ]
    - [ 399416.53,5703120.31 ]
    - [ 402172.7,5700144.5 ]
    - [ 404291.06,5700146.56 ]
    - [ 407776.7,5703492.8 ]
    - [ 411222.6,5703538.6 ]
    - [ 415029.6,5707542.2 ]
    - [ 402876.1,5707401.3 ]
    - [ 404785.3,5711359.4 ]
    - [ 405730.7,5706364.3 ]
    - [ 411794.4,5707942.2 ]
    - [ 409265.0,5709098.6 ]
  bonus:
    - [ 398112.1,5703642.2 ]
    - [ 400818.1,5698171.1 ]
    - [ 402239.3,5705426.3 ]
    - [ 406444.5,5701153.8 ]
    - [ 409983.0,5702743.2 ]
    - [ 406771.2,5708716.8 ]
    - [ 413894.2,5705047.0 ]
    - [ 415196.3,5709601.9 ]
    - [ 416592.9,5703133.2 ]
###########################
#### LEVELS DEFINITION ####
###########################
# PONTIVY
levels:
  - start:
      zoom: 5
      center: [ 270845.15,5904541.30 ]
    player: [ -345683.0352282714,6152332.792990951 ]
    target: [ -330178.07675322174,6117700.949246099 ]
    hints:
      0: You are in the west of the city of Rennes
      6: You are between Lorient and St-Brieuc
      8: You are north of Pontivy
      10: You are between Gouarec and Corlay 
      11: You are in St-Igeaux, double-tap on your position
    pitfalls:
      - [ -354074.93805303966,6144738.938691721 ]
      - [ -332481.4775624775,6140267.372537037 ]
      - [ -344400.87666069705,6143449.063839415 ]
      - [ -335734.18440183485,6135249.425198436 ]
      - [ -351021.59005887026,6129287.336992194 ]
      - [ -341830.0374075777,6127491.066827488 ]
      - [ -332347.0685859482,6128508.634766536 ]
      - [ -334591.7497707198,6149519.8148358 ]
      - [ -341543.72823042,6136346.942591847 ]
    bonus:
      - [ -348074.6313326531,6140114.498480472 ]
      - [ -350367.3899996354,6142681.833370734 ]
      - [ -348173.4528687405,6134202.100545352 ]
      - [ -339571.33420276106,6146127.96639936 ]
      - [ -336542.5169569605,6118925.938958378 ]
      - [ -343359.71517578105,6139266.790875086 ]
      - [ -333120.44969174766,6121170.003909771 ]
      - [ -326402.71403488476,6130024.302039234 ]
      - [ -357192.19324065116,6140933.410330648 ]
      - [ -335082.7828091639,6141802.881527393 ]
  -
  -
  -
  -
  -
  -
  -
  -
  -